"""empty message

Revision ID: 58a488b56c1f
Revises: 88d4ac66f8c5
Create Date: 2024-07-24 20:12:43.093936

"""

from collections.abc import Sequence

from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58a488b56c1f"
down_revision: str | None = "88d4ac66f8c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "transactiontype",
        [
            "TOP_UP",
            "ASSIGN_BUDGET",
            "REVERSE_BUDGET",
            "MOVE_BUDGET",
            "RESERVE",
            "RELEASE",
            "CHARGE_SHORT_JOB",
            "CHARGE_LONG_JOB",
            "CHARGE_STORAGE",
            "REFUND",
        ],
        [
            TableReference(
                table_schema="public", table_name="journal", column_name="transaction_type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "transactiontype",
        [
            "TOP_UP",
            "ASSIGN",
            "RESERVE",
            "RELEASE",
            "CHARGE_SHORT_JOB",
            "CHARGE_LONG_JOB",
            "CHARGE_STORAGE",
            "REFUND",
        ],
        [
            TableReference(
                table_schema="public", table_name="journal", column_name="transaction_type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
