"""empty message

Revision ID: b053b4d195c8
Revises: af57b4dcaecb
Create Date: 2024-07-01 14:03:27.836362

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b053b4d195c8"
down_revision: str | None = "af57b4dcaecb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "queue_message", sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False)
    )
    op.add_column("queue_message", sa.Column("result_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_queue_message_message_id"), "queue_message", ["message_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_queue_message_message_id"), table_name="queue_message")
    op.drop_column("queue_message", "result_id")
    op.drop_column("queue_message", "id")
    # ### end Alembic commands ###
