"""empty message

Revision ID: d4a234cc39b4
Revises: ce4a1945bb55
Create Date: 2024-07-18 18:39:53.328685

"""

from collections.abc import Sequence

from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4a234cc39b4"
down_revision: str | None = "ce4a1945bb55"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "transactiontype",
        [
            "TOPUP",
            "ASSIGN",
            "RESERVE",
            "RELEASE",
            "CHARGE_SHORT_JOBS",
            "CHARGE_LONG_JOBS",
            "CHARGE_STORAGE",
            "REFUND",
        ],
        [
            TableReference(
                table_schema="public", table_name="journal", column_name="transaction_type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "transactiontype",
        [
            "TOPUP",
            "ASSIGN",
            "RESERVE",
            "RELEASE",
            "CHARGE_SHORT_JOBS",
            "CHARGE_LONG_JOBS",
            "CHARGE_STORAGE",
        ],
        [
            TableReference(
                table_schema="public", table_name="journal", column_name="transaction_type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
