"""empty message

Revision ID: b56e853bb310
Revises: 78baff8a1ba2
Create Date: 2024-08-15 15:43:44.202048

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b56e853bb310"
down_revision: str | None = "78baff8a1ba2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_account_parent_id"), "account", ["parent_id"], unique=False)
    op.create_index(op.f("ix_event_job_id"), "event", ["job_id"], unique=False)
    op.create_foreign_key(op.f("fk_job_vlab_id_account"), "job", "account", ["vlab_id"], ["id"])
    op.create_foreign_key(op.f("fk_job_proj_id_account"), "job", "account", ["proj_id"], ["id"])
    op.create_index(op.f("ix_journal_job_id"), "journal", ["job_id"], unique=False)
    op.create_index(op.f("ix_journal_price_id"), "journal", ["price_id"], unique=False)
    op.create_index(op.f("ix_ledger_account_id"), "ledger", ["account_id"], unique=False)
    op.create_index(op.f("ix_ledger_journal_id"), "ledger", ["journal_id"], unique=False)
    op.create_foreign_key(op.f("fk_price_vlab_id_account"), "price", "account", ["vlab_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_price_vlab_id_account"), "price", type_="foreignkey")
    op.drop_index(op.f("ix_ledger_journal_id"), table_name="ledger")
    op.drop_index(op.f("ix_ledger_account_id"), table_name="ledger")
    op.drop_index(op.f("ix_journal_price_id"), table_name="journal")
    op.drop_index(op.f("ix_journal_job_id"), table_name="journal")
    op.drop_constraint(op.f("fk_job_proj_id_account"), "job", type_="foreignkey")
    op.drop_constraint(op.f("fk_job_vlab_id_account"), "job", type_="foreignkey")
    op.drop_index(op.f("ix_event_job_id"), table_name="event")
    op.drop_index(op.f("ix_account_parent_id"), table_name="account")
    # ### end Alembic commands ###
