"""empty message

Revision ID: 259ea6796f7b
Revises: 58a488b56c1f
Create Date: 2024-08-05 15:54:07.495792

"""

from collections.abc import Sequence

from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "259ea6796f7b"
down_revision: str | None = "58a488b56c1f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "servicetype",
        ["STORAGE", "ONESHOT", "LONGRUN"],
        [
            TableReference(table_schema="public", table_name="job", column_name="service_type"),
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        "public",
        "transactiontype",
        [
            "TOP_UP",
            "ASSIGN_BUDGET",
            "REVERSE_BUDGET",
            "MOVE_BUDGET",
            "RESERVE",
            "RELEASE",
            "CHARGE_ONESHOT",
            "CHARGE_LONGRUN",
            "CHARGE_STORAGE",
            "REFUND",
        ],
        [
            TableReference(
                table_schema="public", table_name="journal", column_name="transaction_type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "transactiontype",
        [
            "TOP_UP",
            "ASSIGN_BUDGET",
            "REVERSE_BUDGET",
            "MOVE_BUDGET",
            "RESERVE",
            "RELEASE",
            "CHARGE_SHORT_JOB",
            "CHARGE_LONG_JOB",
            "CHARGE_STORAGE",
            "REFUND",
        ],
        [
            TableReference(
                table_schema="public", table_name="journal", column_name="transaction_type"
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        "public",
        "servicetype",
        ["STORAGE", "SHORT_JOB", "LONG_JOB"],
        [
            TableReference(table_schema="public", table_name="job", column_name="service_type"),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
