"""empty message

Revision ID: c87e5b91d661
Revises: 786828d7f40c
Create Date: 2024-07-24 10:36:17.107775

"""

from collections.abc import Sequence

from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c87e5b91d661"
down_revision: str | None = "786828d7f40c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "servicetype",
        ["STORAGE", "SHORT_JOB", "LONG_JOB"],
        [TableReference(table_schema="public", table_name="job", column_name="service_type")],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        "public",
        "transactiontype",
        [
            "TOP_UP",
            "ASSIGN",
            "RESERVE",
            "RELEASE",
            "CHARGE_SHORT_JOB",
            "CHARGE_LONG_JOB",
            "CHARGE_STORAGE",
            "REFUND",
        ],
        [
            TableReference(
                table_schema="public", table_name="journal", column_name="transaction_type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "transactiontype",
        [
            "TOPUP",
            "ASSIGN",
            "RESERVE",
            "RELEASE",
            "CHARGE_SHORT_JOBS",
            "CHARGE_LONG_JOBS",
            "CHARGE_STORAGE",
            "REFUND",
        ],
        [
            TableReference(
                table_schema="public", table_name="journal", column_name="transaction_type"
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        "public",
        "servicetype",
        ["STORAGE", "SHORT_JOBS", "LONG_JOBS"],
        [TableReference(table_schema="public", table_name="job", column_name="service_type")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
