"""empty message

Revision ID: 1c15c81ce8a8
Revises: b56e853bb310
Create Date: 2024-09-09 15:40:14.071295

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c15c81ce8a8"
down_revision: str | None = "b56e853bb310"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_registry",
        sa.Column("task_name", sa.String(), nullable=False),
        sa.Column("last_run", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_errors", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_duration", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_active_job", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("task_name", name=op.f("pk_task_registry")),
    )
    op.drop_column("job", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("task_registry")
    # ### end Alembic commands ###
