"""empty message

Revision ID: af57b4dcaecb
Revises: 63a1d1c101bd
Create Date: 2024-06-28 17:43:04.226926

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af57b4dcaecb"
down_revision: str | None = "63a1d1c101bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usage", sa.Column("last_alive_at", sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage", "last_alive_at")
    # ### end Alembic commands ###
