"""empty message

Revision ID: 96d8347585d0
Revises: 6f591862ac35
Create Date: 2025-11-05 11:18:38.543653

"""

from collections.abc import Sequence

from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96d8347585d0"
down_revision: str | None = "6f591862ac35"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="servicesubtype",
        new_values=[
            "ION_CHANNEL_BUILD",
            "ML_LLM",
            "ML_RAG",
            "ML_RETRIEVAL",
            "NEURON_MESH_SKELETONIZATION",
            "NOTEBOOK",
            "SINGLE_CELL_BUILD",
            "SINGLE_CELL_SIM",
            "SMALL_CIRCUIT_SIM",
            "STORAGE",
            "SYNAPTOME_BUILD",
            "SYNAPTOME_SIM",
            "SINGLE_SIM",
            "PAIR_SIM",
            "SMALL_SIM",
            "MICROCIRCUIT_SIM",
            "REGION_SIM",
            "SYSTEM_SIM",
            "WHOLE_BRAIN_SIM",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="job", column_name="service_subtype"),
            TableReference(
                table_schema="public", table_name="price", column_name="service_subtype"
            ),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="servicesubtype",
        new_values=[
            "ML_LLM",
            "ML_RAG",
            "ML_RETRIEVAL",
            "NEURON_MESH_SKELETONIZATION",
            "NOTEBOOK",
            "SINGLE_CELL_BUILD",
            "SINGLE_CELL_SIM",
            "SMALL_CIRCUIT_SIM",
            "STORAGE",
            "SYNAPTOME_BUILD",
            "SYNAPTOME_SIM",
            "SINGLE_SIM",
            "PAIR_SIM",
            "SMALL_SIM",
            "MICROCIRCUIT_SIM",
            "REGION_SIM",
            "SYSTEM_SIM",
            "WHOLE_BRAIN_SIM",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="job", column_name="service_subtype"),
            TableReference(
                table_schema="public", table_name="price", column_name="service_subtype"
            ),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
