"""empty message

Revision ID: 69cc5f6c7512
Revises: afe52ed2f369
Create Date: 2025-03-20 13:24:50.338083

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "69cc5f6c7512"
down_revision: str | None = "afe52ed2f369"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discount",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("vlab_id", sa.Uuid(), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("discount", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vlab_id"], ["account.id"], name=op.f("fk_discount_vlab_id_account")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discount")),
    )
    op.create_index(op.f("ix_discount_vlab_id"), "discount", ["vlab_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_discount_vlab_id"), table_name="discount")
    op.drop_table("discount")
    # ### end Alembic commands ###
