"""empty message

Revision ID: a6d8a5264aa3
Revises: b56e853bb310
Create Date: 2025-01-23 14:21:16.162117

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6d8a5264aa3"
down_revision: str | None = "b56e853bb310"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job", sa.Column("user_id", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job", "user_id")
    # ### end Alembic commands ###
