"""empty message

Revision ID: 558b071bccc2
Revises: a4cab64aa586
Create Date: 2025-03-11 16:11:31.757566

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "558b071bccc2"
down_revision: str | None = "a4cab64aa586"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job", sa.Column("name", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job", "name")
    # ### end Alembic commands ###
