"""empty message

Revision ID: 17d02435b28e
Revises: 69cc5f6c7512
Create Date: 2025-03-21 09:22:13.139847

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17d02435b28e"
down_revision: str | None = "69cc5f6c7512"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("journal", sa.Column("discount_id", sa.BigInteger(), nullable=True))
    op.create_index(op.f("ix_journal_discount_id"), "journal", ["discount_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_journal_discount_id_discount"), "journal", "discount", ["discount_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_journal_discount_id_discount"), "journal", type_="foreignkey")
    op.drop_index(op.f("ix_journal_discount_id"), table_name="journal")
    op.drop_column("journal", "discount_id")
    # ### end Alembic commands ###
