"""empty message

Revision ID: ac348615ff34
Revises: c0e195f21eb8
Create Date: 2025-07-14 12:31:25.445096

"""

from collections.abc import Sequence

from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac348615ff34"
down_revision: str | None = "c0e195f21eb8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="servicesubtype",
        new_values=[
            "ML_LLM",
            "ML_RAG",
            "ML_RETRIEVAL",
            "NOTEBOOK",
            "SINGLE_CELL_BUILD",
            "SINGLE_CELL_SIM",
            "SMALL_CIRCUIT_SIM",
            "STORAGE",
            "SYNAPTOME_BUILD",
            "SYNAPTOME_SIM",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="job", column_name="service_subtype"),
            TableReference(
                table_schema="public", table_name="price", column_name="service_subtype"
            ),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="servicesubtype",
        new_values=[
            "STORAGE",
            "NOTEBOOK",
            "SINGLE_CELL_SIM",
            "SINGLE_CELL_BUILD",
            "SYNAPTOME_SIM",
            "SYNAPTOME_BUILD",
            "ML_RETRIEVAL",
            "ML_LLM",
            "ML_RAG",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="job", column_name="service_subtype"),
            TableReference(
                table_schema="public", table_name="price", column_name="service_subtype"
            ),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
