"""empty message

Revision ID: afe52ed2f369
Revises: a4cab64aa586
Create Date: 2025-03-18 16:00:27.684926

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afe52ed2f369"
down_revision: str | None = "a4cab64aa586"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job", sa.Column("name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job", "name")
    # ### end Alembic commands ###
