"""Set identity always on all id columns

Revision ID: 8c8dc5fa244d
Revises: 4f41f2bd0a86
Create Date: 2026-04-13 09:19:17.000000

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c8dc5fa244d"
down_revision: str | None = "4f41f2bd0a86"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLES = ["event", "journal", "ledger", "price", "price_tier", "discount"]


def upgrade() -> None:
    for table in TABLES:
        op.execute(f"ALTER TABLE {table} ALTER COLUMN id SET GENERATED ALWAYS")


def downgrade() -> None:
    for table in TABLES:
        op.execute(f"ALTER TABLE {table} ALTER COLUMN id SET GENERATED BY DEFAULT")
