"""add admin browse indexes

Revision ID: 1efdebc86af2
Revises: a1b2c3d4e5f6
Create Date: 2026-07-21 12:20:33.363274

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1efdebc86af2"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_job_started_at"), "job", ["started_at"], unique=False)
    op.create_index(
        op.f("ix_journal_transaction_datetime"), "journal", ["transaction_datetime"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_journal_transaction_datetime"), table_name="journal")
    op.drop_index(op.f("ix_job_started_at"), table_name="job")
    # ### end Alembic commands ###
