"""Add circuit extraction subtype

Revision ID: 4f41f2bd0a86
Revises: 3642bb905be6
Create Date: 2026-04-10 16:23:39.342327

"""

from collections.abc import Sequence

from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f41f2bd0a86"
down_revision: str | None = "3642bb905be6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="servicesubtype",
        new_values=[
            "ION_CHANNEL_BUILD",
            "ION_CHANNEL_SIM",
            "ML_LLM",
            "NEURON_MESH_SKELETONIZATION",
            "NOTEBOOK",
            "SINGLE_CELL_BUILD",
            "SINGLE_CELL_SIM",
            "SMALL_CIRCUIT_SIM",
            "STORAGE",
            "SYNAPTOME_BUILD",
            "SYNAPTOME_SIM",
            "SINGLE_SIM",
            "PAIR_SIM",
            "SMALL_SIM",
            "MICROCIRCUIT_SIM",
            "REGION_SIM",
            "SYSTEM_SIM",
            "WHOLE_BRAIN_SIM",
            "CIRCUIT_EXTRACTION",
            "ML_RAG",
            "ML_RETRIEVAL",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="job", column_name="service_subtype"),
            TableReference(
                table_schema="public", table_name="price", column_name="service_subtype"
            ),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="servicesubtype",
        new_values=[
            "ION_CHANNEL_BUILD",
            "ION_CHANNEL_SIM",
            "ML_LLM",
            "NEURON_MESH_SKELETONIZATION",
            "NOTEBOOK",
            "SINGLE_CELL_BUILD",
            "SINGLE_CELL_SIM",
            "SMALL_CIRCUIT_SIM",
            "STORAGE",
            "SYNAPTOME_BUILD",
            "SYNAPTOME_SIM",
            "SINGLE_SIM",
            "PAIR_SIM",
            "SMALL_SIM",
            "MICROCIRCUIT_SIM",
            "REGION_SIM",
            "SYSTEM_SIM",
            "WHOLE_BRAIN_SIM",
            "ML_RAG",
            "ML_RETRIEVAL",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="job", column_name="service_subtype"),
            TableReference(
                table_schema="public", table_name="price", column_name="service_subtype"
            ),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
